# Generated by Django 2.1 on 2018-11-21 12:55

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_streams_about_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='about_exam',
        ),
        migrations.AddField(
            model_name='exam_detail',
            name='about_exam',
            field=froala_editor.fields.FroalaField(blank=True, max_length=2, null=True),
        ),
    ]
